------------------------ ITEMS_TYPE ----------------------------
DROP TABLE IF EXISTS ITEMS_TYPE;
DROP SEQUENCE IF EXISTS ITEMS_TYPE_SEQ;

CREATE SEQUENCE ITEMS_TYPE_SEQ;

CREATE TABLE ITEMS_TYPE (
   items_type_id INT NOT NULL, 
   description VARCHAR(50) NOT NULL, 
   price VARCHAR(20) NOT NULL, 
   duration VARCHAR(20) NOT NULL, 
   image BLOB, 
   currency_type VARCHAR(20) NOT NULL, 
   ingredients VARCHAR(20) NOT NULL, 
   active_flag VARCHAR(20) NOT NULL,
   MODIFIED_TS TIMESTAMP (6),
   CREATED_TS TIMESTAMP (6)
);

ALTER TABLE ITEMS_TYPE ADD PRIMARY KEY (items_type_id);

------------------------ USERS ----------------------------

DROP TABLE IF EXISTS USERS;
DROP SEQUENCE IF EXISTS USERS_SEQ;

CREATE SEQUENCE USERS_SEQ;

CREATE TABLE USERS (
   user_id INT NOT NULL, 
   user_name VARCHAR(50) NOT NULL, 
   password VARCHAR(80) NOT NULL,
   role VARCHAR(20) NOT NULL,
   active_flag VARCHAR(20) NOT NULL,
   MODIFIED_TS TIMESTAMP (6),
   CREATED_TS TIMESTAMP (6)
);

ALTER TABLE USERS ADD PRIMARY KEY (user_id);

INSERT INTO USERS VALUES (1000, 'ADMIN', '$2a$10$.qaM6dKo/GqQR86mgfzF3eblRwX1V42eVAhDpRsSSX07868/aTjOa', 'ROLE_ADMIN', 'Y', SYSDATE, SYSDATE);

------------------------ ITEMS_TRANSACTION ----------------------------

DROP TABLE IF EXISTS ITEMS_TRANSACTION;
DROP SEQUENCE IF EXISTS ITEMS_TRANSACTION_SEQ;

CREATE SEQUENCE ITEMS_TRANSACTION_SEQ;

CREATE TABLE ITEMS_TRANSACTION (
   items_transaction_id INT NOT NULL, 
   items_type_id INT NOT NULL,
   table_no INT NOT NULL,
   total_quantity VARCHAR(20) NOT NULL, 
   order_status VARCHAR(20) NOT NULL,
   user_id INT,
   MODIFIED_TS TIMESTAMP (6),
   CREATED_TS TIMESTAMP (6)
);

ALTER TABLE ITEMS_TRANSACTION ADD PRIMARY KEY (items_transaction_id);
ALTER TABLE ITEMS_TRANSACTION ADD CONSTRAINT FK_ITEM_TYPE_IDX_PK_ITEM_TX FOREIGN KEY ( items_type_id ) REFERENCES ITEMS_TYPE( items_type_id );
ALTER TABLE ITEMS_TRANSACTION ADD CONSTRAINT FK_USERS_IDX_PK_ITEM_TX FOREIGN KEY ( user_id ) REFERENCES USERS( user_id );
COMMIT;